### ISSUE TITLE
Form validation issue

### ISSUE THREAD

**Issue by AndrewDuarte** [TroopAffiliate/TroopAffiliate_Site#4]
After testing the form I found some validation issues. If you input `test@email` into the text field and press `enter`, you're redirected to the mail chip validation page.

# Required result:
You input something like `test@email` or `someone@testing` (as an example) you are **not** redirected to the MailChimp validation page. Instead the form label with display an error message.

**Comment by shuvaramva** [comment]
This has been fixed. Please confirm.

**Comment by AndrewDuarte** [comment]
Tested. Seems to be working now. Woohoo! Good work! :)
